# Generated by Django 5.1.4 on 2025-01-09 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='car_images/')),
                ('price_per_day', models.FloatField()),
                ('rating', models.FloatField()),
                ('car_make', models.CharField(max_length=50)),
                ('car_model', models.CharField(max_length=50)),
                ('car_year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('is_recommended', models.BooleanField(default=False)),
            ],
        ),
    ]
